data = [
    {
        "name": "Instagram",
        "description": "Social media platform",
        "follower_count": 672,
        "country": "US",
    },
    {
        "name": "Cristiano Ronaldo",
        "description": "Footballer. Known as CR7",
        "follower_count": 628,
        "country": "PT",
    },
    {
        "name": "Selena Gomez",
        "description": "Singer and actress",
        "follower_count": 423,
        "country": "US",
    },
    {
        "name": "Lionel Messi",
        "description": "Footballer. Plays for Inter Miami CF",
        "follower_count": 504,
        "country": "AR",
    },
    {
        "name": "Kylie Jenner",
        "description": "Reality TV star and entrepreneur",
        "follower_count": 399,
        "country": "US",
    },
    {
        "name": "Dwayne Johnson",
        "description": "Actor and former professional wrestler",
        "follower_count": 395,
        "country": "US",
    },
    {
        "name": "Ariana Grande",
        "description": "Singer and actress",
        "follower_count": 376,
        "country": "US",
    },
    {
        "name": "Kim Kardashian",
        "description": "Reality TV star and media personality",
        "follower_count": 364,
        "country": "US",
    },
    {
        "name": "Beyoncé",
        "description": "Singer and entertainer",
        "follower_count": 318,
        "country": "US",
    },
    {
        "name": "Khaby Lame",
        "description": "Content creator on TikTok and Instagram",
        "follower_count": 161,
        "country": "SN",
    },
    {
        "name": "Taylor Swift",
        "description": "Singer-songwriter and pop icon",
        "follower_count": 282,
        "country": "US",
    },
    {
        "name": "Justin Bieber",
        "description": "Pop singer and songwriter",
        "follower_count": 292,
        "country": "CA",
    },
    {
        "name": "Neymar Jr",
        "description": "Brazilian football star",
        "follower_count": 221,
        "country": "BR",
    },
    {
        "name": "Kendall Jenner",
        "description": "Model and reality TV personality",
        "follower_count": 295,
        "country": "US",
    },
    {
        "name": "Nike",
        "description": "Global sportswear and footwear brand",
        "follower_count": 305,
        "country": "US",
    },
    {
        "name": "National Geographic",
        "description": "Photography and science media brand",
        "follower_count": 278,
        "country": "US",
    },
    {
        "name": "Billie Eilish",
        "description": "Grammy-winning pop and alternative artist",
        "follower_count": 113,
        "country": "US",
    },
    {
        "name": "Cardi B",
        "description": "Rapper and media personality",
        "follower_count": 159,
        "country": "US",
    },
    {
        "name": "LeBron James",
        "description": "NBA basketball legend",
        "follower_count": 160,
        "country": "US",
    },
    {
        "name": "Virat Kohli",
        "description": "Indian cricket superstar",
        "follower_count": 269,
        "country": "IN",
    },
    {
        "name": "Priyanka Chopra",
        "description": "Actress and global icon",
        "follower_count": 91,
        "country": "IN",
    },
    {
        "name": "BTS Official",
        "description": "K-pop supergroup",
        "follower_count": 73,
        "country": "KR",
    },
    {
        "name": "Zendaya",
        "description": "Actress and fashion icon",
        "follower_count": 183,
        "country": "US",
    },
    {
        "name": "Elon Musk",
        "description": "Tech billionaire and CEO of Tesla and SpaceX",
        "follower_count": 67,
        "country": "US",
    },
    {
        "name": "Shakira",
        "description": "Colombian singer and dancer",
        "follower_count": 85,
        "country": "CO",
    },
    {
        "name": "NASA",
        "description": "US space exploration agency",
        "follower_count": 97,
        "country": "US",
    },
    {
        "name": "Real Madrid CF",
        "description": "Spanish football club",
        "follower_count": 55,
        "country": "ES",
    },
    {
        "name": "FC Barcelona",
        "description": "Spanish football club",
        "follower_count": 108,
        "country": "ES",
    },
    {
        "name": "Maluma",
        "description": "Colombian reggaeton and pop singer",
        "follower_count": 62,
        "country": "CO",
    },
    {
        "name": "Miley Cyrus",
        "description": "Pop rock singer and actress",
        "follower_count": 211,
        "country": "US",
    },
]